import { useState } from 'react';
import { ArrowLeft, ShieldPlus, Pencil, Play, Check, TriangleAlert, MessageSquare, CirclePause, FileCheck2, Info, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Alert,AlertTitle,AlertDescription } from '@/components/ui/alert';
import { Skeleton } from '@/components/ui/skeleton';
import { PatientCase } from './data';
import { Status, SourceButton } from './primitives';
type Props={mode:'demo'|'live';onMessage:(s:string)=>void;patient:PatientCase;onBack:()=>void;onContext:()=>void;onSource:(id:string)=>void;onEdit:(s:string)=>void;onRun:()=>void;onApprove:()=>void;onEscalate:()=>void;onReject:()=>void;onFollowUp:(message?:string)=>void;busy:boolean};
export function CasePanel({mode,onMessage,patient:p,onBack,onContext,onSource,onEdit,onRun,onApprove,onEscalate,onReject,onFollowUp,busy}:Props){
 const ready=p.status==='review'; const running=p.status==='running'; const blocked=p.status==='blocked';const terminal=['sent','rejected','escalated'].includes(p.status);const clarification=mode==='live'?p.ai?.action==='clarify':p.scenario==='missing'&&!p.followUp;
 return <section className="case-panel" aria-label="Selected patient"><div className="case-scroll" key={p.id}><button className="back-button" onClick={onBack}><ArrowLeft size={16}/>Messages</button><header className="patient-header"><div><div className="patient-heading"><h2>{p.name}</h2><Status status={p.status}/></div><p>{p.sex}<span>·</span>{p.age} years<span>·</span>{p.id}</p></div><Button variant="ghost" size="sm" onClick={onContext}>Patient details</Button></header><div className="content-label"><h3>Patient message</h3><span>Today at {p.time}</span></div>{mode==='live'&&['new','paused'].includes(p.status)?<><Textarea aria-label="Fictional patient message" className="message-editor" value={p.message} maxLength={2000} disabled={busy} onChange={e=>onMessage(e.target.value)}/><p className="message-help">Edit this fictional message to test retrieval and generation. Do not enter real patient information.</p></>:<div className="original-message">{p.message}</div>}{p.followUp&&<div className="followup-message"><div className="content-label"><h3>Patient follow-up</h3><span>Simulated response</span></div><p>{p.followUp}</p></div>}
 {ready&&<><div className="content-label draft-label"><h3>{clarification?'Clarification draft':'AI draft reply'}</h3><span><Pencil size={13}/>Editable draft</span></div><Textarea aria-label="AI draft reply" className="draft-editor" value={p.draft} onChange={e=>onEdit(e.target.value)}/><div className="source-caption">Cited sources · select to verify</div><div className="source-grid">{p.sources.map((id,i)=><SourceButton key={id} id={id} index={i} patient={p} onClick={()=>onSource(id)}/>)}</div></>}
 {(p.status==='new'||p.status==='paused')&&<div className="start-workflow">{p.status==='paused'?<CirclePause size={27}/>:<ShieldPlus size={27}/>}<h3>{p.status==='paused'?'Ready to pick up where you left off':'Ready for a closer look'}</h3><p>{mode==='live'?'Retrieve matching sources, generate a draft with DeepSeek, then review its citations.':p.status==='paused'?'The case and its previous activity are saved. Resume the simulated workflow with the available information.':'Run the simulated workflow to retrieve context, check sources and prepare the next step.'}</p><Button disabled={busy} onClick={onRun}><Play data-icon="inline-start"/>{p.status==='paused'?'Resume triage':'Run triage'}</Button>{busy&&<small>Another case is being processed.</small>}</div>}
 {running&&<div className="running-state" role="status"><div className="content-label"><h3>Working through the case</h3><span>{mode==='live'?'Retrieval + DeepSeek':'Simulated workflow'}</span></div><Skeleton className="h-4 w-3/4"/><Skeleton className="h-4 w-full"/><Skeleton className="h-4 w-2/3"/><p>Checking the message, patient context and applicable policy…</p></div>}
 {p.runError&&<Alert className="live-error" variant="destructive"><TriangleAlert/><AlertTitle>Live AI could not complete this case</AlertTitle><AlertDescription>{p.runError} No draft was generated. You can retry after resolving the issue.</AlertDescription></Alert>}
 {blocked&&<Alert className="safety-alert"><TriangleAlert/><AlertTitle>{mode==='live'?'Human review required':p.scenario==='injection'?'Untrusted instructions blocked':p.scenario==='unavailable'?'Required evidence is unavailable':'Routine drafting has stopped'}</AlertTitle><AlertDescription>{mode==='live'?p.summary:p.scenario==='injection'?'No other patient record was accessed. Staff must review this request.':p.scenario==='unavailable'?'The agent cannot produce a supported reply. Route this case to staff for manual handling.':'This case requires immediate human assessment. The agent cannot approve or send a routine reply.'}</AlertDescription></Alert>}
 {p.status==='awaiting'&&<div className="result-state waiting"><MessageSquare/><h3>Waiting for patient information</h3><p>Your clarification was approved. The workflow is paused and this case is saved.</p><div className="approved-text">{p.draft}</div><FollowUpForm key={p.id} mode={mode} onSubmit={onFollowUp}/></div>}
 {terminal&&<div className={`result-state result-${p.status}`}>{p.status==='sent'?<FileCheck2/>:p.status==='rejected'?<X/>:<TriangleAlert/>}<h3>{p.status==='sent'?'Reply approved':p.status==='rejected'?'Draft rejected':'Handoff recorded'}</h3><p>{p.status==='sent'?'Mia Chen approved this response. Sending was simulated.':p.status==='rejected'?'This case is closed without sending a response.':'The assigned team and your handoff note are saved with this case. No patient reply was sent.'}</p>{p.status==='sent'?<div className="approved-text">{p.draft}</div>:<div className="approved-text">{p.reviewerNote}</div>}</div>}
 {p.ai&&<div className="generation-receipt"><span>{p.ai.provenance==='llm'?p.ai.model:'Deterministic safety control'}</span><span>{p.ai.retrieval.eligibleDocuments===0?'Model not called':`${p.ai.retrieval.method} · ${p.ai.retrieved.length} retrieved sources`}</span><span>{(p.ai.elapsedMs/1000).toFixed(1)}s</span></div>}
 {mode==='live'&&(ready||blocked)&&<Button className="rerun-button" variant="outline" disabled={busy} onClick={onRun}>Run again with Live AI</Button>}
 </div>{ready&&<footer className="review-bar"><div className="review-actions"><Button disabled={!p.draft.trim()} onClick={onApprove}><Check data-icon="inline-start"/>Approve</Button><Button variant="ghost" onClick={onReject}>Reject</Button><Button variant="outline" onClick={onEscalate}>Escalate</Button></div></footer>}{blocked&&<footer className="review-bar blocked-bar"><span><LockMessage/>Human action required</span><Button variant="destructive" onClick={onEscalate}>Escalate to staff</Button></footer>}</section>
}
function LockMessage(){return <Info size={15}/>}

function FollowUpForm({mode,onSubmit}:{mode:'demo'|'live';onSubmit:(message?:string)=>void}){
 const [text,setText]=useState('');
 if(mode==='demo')return <Button variant="outline" onClick={()=>onSubmit()}>Add demo patient response</Button>;
 return <div className="followup-form"><Textarea aria-label="Fictional patient follow-up" placeholder="Write a fictional patient follow-up…" maxLength={2000} value={text} onChange={e=>setText(e.target.value)}/><Button variant="outline" disabled={text.trim().length<5} onClick={()=>onSubmit(text)}>Add patient follow-up</Button></div>
}
