import { ArrowLeft, ShieldCheck, ShieldPlus, Pencil, Play, Check, TriangleAlert, MessageSquare, CirclePause, FileCheck2, Info, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Textarea } from '@/components/ui/textarea';
import { Alert,AlertTitle,AlertDescription } from '@/components/ui/alert';
import { Skeleton } from '@/components/ui/skeleton';
import { PatientCase } from './data';
import { Status, SourceButton } from './primitives';
type Props={patient:PatientCase;reviewed:boolean;setReviewed:(v:boolean)=>void;onBack:()=>void;onContext:()=>void;onSource:(id:string)=>void;onEdit:(s:string)=>void;onRun:()=>void;onApprove:()=>void;onEscalate:()=>void;onReject:()=>void;onFollowUp:()=>void;busy:boolean};
export function CasePanel({patient:p,reviewed,setReviewed,onBack,onContext,onSource,onEdit,onRun,onApprove,onEscalate,onReject,onFollowUp,busy}:Props){
 const ready=p.status==='review'; const running=p.status==='running'; const blocked=p.status==='blocked';const terminal=['sent','rejected','escalated'].includes(p.status);
 return <section className="case-panel" aria-label="Selected patient"><div className="case-scroll" key={p.id}><button className="back-button" onClick={onBack}><ArrowLeft size={16}/>Messages</button><header className="patient-header"><div><div className="patient-heading"><h2>{p.name}</h2><Status status={p.status}/></div><p>{p.sex}<span>·</span>{p.age} years<span>·</span>{p.id}</p></div><Button variant="ghost" size="sm" onClick={onContext}>Patient details</Button></header><div className="content-label"><h3>Patient message</h3><span>Today at {p.time}</span></div><div className="original-message">{p.message}</div>{p.followUp&&<div className="followup-message"><div className="content-label"><h3>Patient follow-up</h3><span>Simulated response</span></div><p>{p.followUp}</p></div>}
 {(ready||blocked||terminal||p.status==='awaiting')&&<div className={`triage-summary ${p.urgency==='Urgent'||blocked?'urgent-summary':''}`}><div className="summary-label"><ShieldCheck size={16}/><h3>Triage summary</h3><span>Simulated</span></div><h4>{p.urgency}<span>·</span>{p.category}</h4><p>{p.summary}</p><ol>{p.steps.map((step,i)=><li key={step}><span>{i+1}</span>{step}</li>)}</ol></div>}
 {ready&&<><div className="content-label draft-label"><h3>{p.scenario==='missing'&&!p.followUp?'Clarification draft':'AI draft reply'}</h3><span><Pencil size={13}/>Editable draft</span></div><Textarea aria-label="AI draft reply" className="draft-editor" value={p.draft} onChange={e=>{onEdit(e.target.value);setReviewed(false)}}/><div className="source-caption">Cited sources · select to verify</div><div className="source-grid">{p.sources.map((id,i)=><SourceButton key={id} id={id} index={i} patient={p} onClick={()=>onSource(id)}/>)}</div></>}
 {(p.status==='new'||p.status==='paused')&&<div className="start-workflow">{p.status==='paused'?<CirclePause size={27}/>:<ShieldPlus size={27}/>}<h3>{p.status==='paused'?'Ready to pick up where you left off':'Ready for a closer look'}</h3><p>{p.status==='paused'?'The case and its previous activity are saved. Resume the simulated workflow with the available information.':'Run the simulated workflow to retrieve context, check sources and prepare the next step.'}</p><Button disabled={busy} onClick={onRun}><Play data-icon="inline-start"/>{p.status==='paused'?'Resume triage':'Run triage'}</Button>{busy&&<small>Another case is being processed.</small>}</div>}
 {running&&<div className="running-state" role="status"><div className="content-label"><h3>Working through the case</h3><span>Simulated workflow</span></div><Skeleton className="h-4 w-3/4"/><Skeleton className="h-4 w-full"/><Skeleton className="h-4 w-2/3"/><p>Checking the message, patient context and applicable policy…</p></div>}
 {blocked&&<Alert className="safety-alert"><TriangleAlert/><AlertTitle>{p.scenario==='injection'?'Untrusted instructions blocked':p.scenario==='unavailable'?'Required evidence is unavailable':'Routine drafting has stopped'}</AlertTitle><AlertDescription>{p.scenario==='injection'?'No other patient record was accessed. Staff must review this request.':p.scenario==='unavailable'?'The agent cannot produce a supported reply. Route this case to staff for manual handling.':'This case requires immediate human assessment. The agent cannot approve or send a routine reply.'}</AlertDescription></Alert>}
 {p.status==='awaiting'&&<div className="result-state waiting"><MessageSquare/><h3>Waiting for patient information</h3><p>Your clarification was approved. The workflow is paused and this case is saved.</p><div className="approved-text">{p.draft}</div><Button variant="outline" onClick={onFollowUp}>Add demo patient response</Button></div>}
 {terminal&&<div className={`result-state result-${p.status}`}>{p.status==='sent'?<FileCheck2/>:p.status==='rejected'?<X/>:<TriangleAlert/>}<h3>{p.status==='sent'?'Reply approved':p.status==='rejected'?'Draft rejected':'Handoff recorded'}</h3><p>{p.status==='sent'?'Mia Chen approved this response. Sending was simulated.':p.status==='rejected'?'This case is closed without sending a response.':'The assigned team and your handoff note are saved in the audit log. No patient reply was sent.'}</p>{p.status==='sent'?<div className="approved-text">{p.draft}</div>:<div className="approved-text">{p.reviewerNote}</div>}</div>}
 </div>{ready&&<footer className="review-bar"><label className="review-check"><Checkbox checked={reviewed} onCheckedChange={v=>setReviewed(v===true)}/>I reviewed the patient details and cited sources</label><div className="review-actions"><Button variant="outline" onClick={onEscalate}>Escalate</Button><Button variant="ghost" onClick={onReject}>Reject</Button><Button disabled={!reviewed||!p.draft.trim()} onClick={onApprove}><Check data-icon="inline-start"/>{p.scenario==='missing'&&!p.followUp?'Approve clarification':'Approve & send'}</Button></div></footer>}{blocked&&<footer className="review-bar blocked-bar"><span><LockMessage/>Human action required</span><Button variant="destructive" onClick={onEscalate}>Escalate to staff</Button></footer>}</section>
}
function LockMessage(){return <Info size={15}/>}
