import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { PatientCase,Event,sourceFor } from './data';
import { SourceButton,StepDot } from './primitives';
export function PatientDetails({patient:p}:{patient:PatientCase}){return <><div className="context-section"><h3>Patient details</h3><dl><div><dt>Patient ID</dt><dd>{p.id}</dd></div><div><dt>Age</dt><dd>{p.age} years</dd></div><div><dt>Care team</dt><dd>Dr. Emily Koh</dd></div></dl></div><div className="context-section"><h3>Current medication</h3><p>{p.medication}</p><small>From the simulated patient record</small></div><div className="context-section"><h3>Allergies</h3><p>{p.allergies}</p></div><div className="context-section"><h3>Next appointment</h3><p>{p.appointment}</p></div></>}
export function ContextPanel({patient,events,tab,setTab,onSource,onAudit}:{patient:PatientCase;events:Event[];tab:string;setTab:(s:string)=>void;onSource:(id:string)=>void;onAudit:()=>void}){
 const trace=events.filter(e=>e.caseId===patient.id).slice(-7);
 return <aside className="context-panel"><Tabs value={tab} onValueChange={setTab}><TabsList variant="line" className="context-tabs"><TabsTrigger value="context">Patient context</TabsTrigger><TabsTrigger value="evidence">Evidence</TabsTrigger></TabsList><TabsContent value="context"><PatientDetails patient={patient}/><div className="context-section"><h3>Sources</h3><div className="context-sources">{patient.sources.map(id=><SourceButton key={id} id={id} patient={patient} onClick={()=>onSource(id)}/>)}{!patient.sources.length&&<p>No source retrieved yet.</p>}</div></div></TabsContent><TabsContent value="evidence"><div className="context-section evidence-stack"><h3>Supporting evidence</h3>{patient.sources.map((id,i)=><article key={id} className="evidence-card"><span className="source-number">{i+1}</span><h4>{sourceFor(id,patient)?.title}</h4><small>{sourceFor(id,patient)?.kind}</small><blockquote>{sourceFor(id,patient)?.excerpt}</blockquote><Button size="sm" variant="link" onClick={()=>onSource(id)}>View source details</Button></article>)}{!patient.sources.length&&<p>No verified source available.</p>}</div></TabsContent></Tabs><div className="context-section activity"><div className="activity-title"><h3>Agent activity</h3>{trace.length>0&&<button onClick={onAudit}>View log</button>}</div>{trace.map((e,i)=><div className="activity-item" key={e.id}><StepDot done={!(i===trace.length-1&&['review','blocked','awaiting','paused'].includes(patient.status))}/><div><strong>{e.action}</strong><small>{e.id.startsWith('seed')?'Demo · 10:42':new Date(e.at).toLocaleTimeString('en-SG',{hour:'2-digit',minute:'2-digit',hour12:false})}</small></div></div>)}{!trace.length&&<p>Run triage to begin the activity trace.</p>}</div></aside>
}
