import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Field,FieldLabel,FieldDescription,FieldGroup } from '@/components/ui/field';
import { Select,SelectContent,SelectGroup,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { FileText, ShieldCheck } from 'lucide-react';
import { PatientCase,Source,seedCases } from './data';
import { PatientDetails } from './context-panel';
export type DialogKind='escalate'|'reset'|'guide'|'patient'|null;
export function SourceDialog({source,onClose}:{source:Source|undefined;onClose:()=>void}){return <Dialog open={!!source} onOpenChange={v=>!v&&onClose()}><DialogContent className="source-dialog"><DialogHeader><div className="dialog-icon"><FileText/></div><DialogTitle>{source?.title}</DialogTitle><DialogDescription>{source?.kind} · {source?.version}</DialogDescription></DialogHeader><div className="source-meta">Source ID <strong>{source?.id}</strong></div><blockquote className="source-excerpt">{source?.excerpt}</blockquote><div className="source-rationale">{source?.quote&&<><h3>Exact quote used by the model</h3><blockquote>{source.quote}</blockquote></>}<h3>How this supports the response</h3><p>{source?.applies}</p></div><p className="dialog-footnote">Fictional teaching source. Check that its content supports the draft; source matching alone does not verify clinical correctness.</p><DialogFooter><Button onClick={onClose}>Done reviewing</Button></DialogFooter></DialogContent></Dialog>}
export function ActionDialogs({mode,kind,onClose,patient,note,setNote,team,setTeam,onConfirm,onSelect}:{mode:'demo'|'live';kind:DialogKind;onClose:()=>void;patient:PatientCase;note:string;setNote:(s:string)=>void;team:string;setTeam:(s:string)=>void;onConfirm:()=>void;onSelect:(p:PatientCase)=>void}){
 const decision=kind==='escalate';
 const title=kind==='escalate'?'Escalate this case':kind==='reset'?'Reset the demo workspace?':kind==='patient'?`${patient.name} · Patient context`:'Try the SafeTriage workflow';
 const description=kind==='escalate'?'Assign the case and leave the next reviewer a clear handoff.':kind==='reset'?'This clears local demo edits and decisions, then restores the six fictional cases.':kind==='patient'?'Fictional patient record for this demonstration.':mode==='live'?'DeepSeek drafts from retrieved fictional sources. Inspect every citation before approving; no real patient message is sent.':'Six fictional cases demonstrate fixed workflows. Switch to Live AI for retrieval and model-generated drafts.';
 return <Dialog open={kind!==null} onOpenChange={v=>!v&&onClose()}><DialogContent className={kind==='guide'?'guide-dialog':'action-dialog'}><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription></DialogHeader>{decision&&<FieldGroup>{kind==='escalate'&&<Field><FieldLabel htmlFor="handoff-team">Assign to</FieldLabel><Select value={team} onValueChange={setTeam}><SelectTrigger id="handoff-team"><SelectValue/></SelectTrigger><SelectContent><SelectGroup><SelectItem value="On-call clinician">On-call clinician</SelectItem><SelectItem value="Nursing team">Nursing team</SelectItem><SelectItem value="Security review team">Security review team</SelectItem></SelectGroup></SelectContent></Select></Field>}<Field><FieldLabel htmlFor="decision-note">Handoff note <span aria-hidden="true">*</span></FieldLabel><Textarea id="decision-note" value={note} onChange={e=>setNote(e.target.value)} placeholder="Summarize the concern and the action needed…" rows={4}/><FieldDescription>A reason is required and will be saved with this case.</FieldDescription></Field></FieldGroup>}{kind==='patient'&&<div className="patient-dialog-content"><PatientDetails patient={patient}/></div>}{kind==='guide'&&<><div className="guide-flow"><span>1. Select a case</span><span>2. Run triage</span><span>3. Review & act</span></div><div className="guide-cases">{seedCases.map(p=><button key={p.id} onClick={()=>{onSelect(p);onClose()}}><strong>{p.name}</strong><span>{p.scenario==='refill'?'Edit a draft and approve a reply':p.scenario==='urgent'?'Trigger a safety stop and escalation':p.scenario==='missing'?'Ask for details, then resume the case':p.scenario==='appointment'?'Confirm a recorded appointment':p.scenario==='injection'?'Block an unauthorized instruction':'Handle a missing evidence source'}</span></button>)}</div><div className="guide-note"><ShieldCheck size={18}/><p>Changes are saved in this browser only. All patients, policies and sends are simulated. Use Reset demo to start again.</p></div></>}{kind!=='guide'&&<DialogFooter><Button variant="outline" onClick={onClose}>{kind==='patient'?'Close':'Cancel'}</Button>{kind!=='patient'&&<Button variant={kind==='escalate'||kind==='reset'?'destructive':'default'} disabled={decision&&!note.trim()} onClick={onConfirm}>{kind==='escalate'?'Record escalation':'Reset demo'}</Button>}</DialogFooter>}</DialogContent></Dialog>
}
