import { Search, Inbox, LockKeyhole, TriangleAlert } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Tabs,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { Empty,EmptyHeader,EmptyTitle,EmptyDescription } from '@/components/ui/empty';
import { PatientCase } from './data';
import { Status, Avatar } from './primitives';
export function InboxPanel({cases,selected,query,onQuery,filter,onFilter,onSelect,view}:{cases:PatientCase[];selected:string;query:string;onQuery:(s:string)=>void;filter:string;onFilter:(s:string)=>void;onSelect:(p:PatientCase)=>void;view:string}){
 const inView=cases.filter(p=>view==='escalations'?p.status==='escalated'||p.status==='blocked':true);
 const visible=inView.filter(p=>(`${p.name} ${p.subject} ${p.id}`).toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='review'&&p.status==='review'||filter==='urgent'&&p.urgency==='Urgent'));
 return <section className="inbox-panel" aria-label="Patient messages"><div className="inbox-controls"><div className="section-title"><h2>{view==='escalations'?'Flagged cases':'Messages'}</h2><span className="count-circle">{inView.length}</span></div><div className="search-input"><Search size={17}/><Input aria-label="Search messages" placeholder="Search messages" value={query} onChange={e=>onQuery(e.target.value)}/></div><Tabs value={filter} onValueChange={onFilter}><TabsList className="inbox-filters"><TabsTrigger value="all">All</TabsTrigger><TabsTrigger value="review">Needs review</TabsTrigger><TabsTrigger value="urgent">Urgent</TabsTrigger></TabsList></Tabs></div><div className="message-list">{visible.map(p=><button key={p.id} className={`message-row ${p.id===selected?'selected':''}`} onClick={()=>onSelect(p)}><Avatar patient={p}/><span className="message-copy"><span className="message-name"><strong>{p.name}</strong><time>{p.time}</time></span><strong className="message-subject">{p.subject}</strong><span className="message-preview">{p.followUp||p.message}</span><span className="row-status"><Status status={p.status}/>{p.urgency==='Urgent'&&<span className="urgent-tag"><TriangleAlert size={11}/>Urgent</span>}</span></span></button>)}{!visible.length&&<Empty className="empty-list"><EmptyHeader><Inbox/><EmptyTitle>No matching messages</EmptyTitle><EmptyDescription>Try another name or filter. Cases you finish remain in the main inbox.</EmptyDescription></EmptyHeader></Empty>}</div><div className="queue-footer"><LockKeyhole size={13}/>{cases.length} fictional patients · local demo</div></section>
}
