import { Download, BookOpen, FileClock, ExternalLink } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import { Empty,EmptyHeader,EmptyTitle,EmptyDescription } from '@/components/ui/empty';
import { Event,sources } from './data';
export function ResourceView({view,events,query,onQuery,onSource,onExport}:{view:string;events:Event[];query:string;onQuery:(s:string)=>void;onSource:(s:string)=>void;onExport:()=>void}){
 const filtered=events.filter(e=>`${e.caseId} ${e.actor} ${e.action} ${e.detail}`.toLowerCase().includes(query.toLowerCase())).slice().reverse();
 return <section className="resource-view">{view==='audit'?<><div className="resource-header"><div><h2>A record of every decision</h2><p>Tool activity, source retrieval and human decisions in this demo workspace.</p></div><Button variant="outline" onClick={onExport}><Download data-icon="inline-start"/>Export log</Button></div><div className="resource-toolbar"><Input aria-label="Search audit log" placeholder="Search case, action or reviewer" value={query} onChange={e=>onQuery(e.target.value)}/><span>{filtered.length} events</span></div><Table className="audit-table"><TableHeader><TableRow><TableHead>Time</TableHead><TableHead>Case</TableHead><TableHead>Action</TableHead><TableHead>Actor</TableHead><TableHead>Details</TableHead></TableRow></TableHeader><TableBody>{filtered.map(e=><TableRow key={e.id}><TableCell className="nowrap">{e.id.startsWith('seed')?'Demo 10:42':new Date(e.at).toLocaleTimeString('en-SG',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false})}</TableCell><TableCell className="nowrap">{e.caseId}</TableCell><TableCell><strong>{e.action}</strong></TableCell><TableCell>{e.actor}</TableCell><TableCell><details><summary>View details</summary><p>{e.detail}</p></details></TableCell></TableRow>)}</TableBody></Table>{!filtered.length&&<Empty><EmptyHeader><FileClock/><EmptyTitle>No matching events</EmptyTitle><EmptyDescription>Try another search or complete a demo action.</EmptyDescription></EmptyHeader></Empty>}</>:<><div className="resource-header"><div><h2>Knowledge you can inspect</h2><p>A small, controlled source library for the six fictional cases.</p></div><span className="library-count">{sources.length} sources</span></div><div className="knowledge-notice"><BookOpen size={20}/><p>These policies and patient records were written for this course prototype. They are not clinical guidelines.</p></div><div className="knowledge-list">{sources.map(s=><button key={s.id} onClick={()=>onSource(s.id)}><span className="document-icon"><BookOpen size={22}/></span><span><strong>{s.title}</strong><small>{s.kind} · {s.version}</small><p>{s.applies}</p></span><span className="document-id">{s.id}</span></button>)}</div><div className="reference-links"><h3>Interaction research</h3><p>Public product documentation informed the interaction patterns, not the simulated clinical policies.</p><div>{[['Artera Smart Inbox','https://artera.helpjuice.com/collaborative-inbox/smart-inbox'],['Artera Staff AI Co-Pilot','https://artera.helpjuice.com/collaborative-inbox/staff-ai-co-pilot'],['Epic Art','https://www.epic.com/software/art/'],['Abridge Linked Evidence','https://support.abridge.com/hc/en-us/articles/30235128433811-Verify-a-Note-With-Linked-Evidence']].map(([label,url])=><a key={url} href={url} target="_blank" rel="noreferrer">{label}<ExternalLink size={13}/></a>)}</div></div></>}</section>
}
