'use client';
import { useEffect, useRef, useState } from 'react';
import { toast } from 'sonner';
import { seedCases, initialEvents, PatientCase, Event, CaseStatus } from './data';
const STORAGE='safetriage-demo-v1';
export function useDemoStore(){
 const [cases,setCases]=useState<PatientCase[]>(seedCases); const [events,setEvents]=useState<Event[]>(initialEvents); const [loaded,setLoaded]=useState(false); const timers=useRef<ReturnType<typeof setTimeout>[]>([]); const busy=useRef(false);
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE);if(raw){const s=JSON.parse(raw);if(s.version===1&&Array.isArray(s.cases)&&s.cases.length===seedCases.length&&s.cases.every((p:PatientCase)=>seedCases.some(x=>x.id===p.id)&&typeof p.draft==='string')&&Array.isArray(s.events)){setCases(s.cases.map((p:PatientCase)=>({...p,status:p.status==='running'?'paused':p.status})));setEvents(s.events)}}}catch{/* A corrupt browser demo is safely replaced with fixtures. */}setLoaded(true);return()=>timers.current.forEach(clearTimeout)},[]);
 useEffect(()=>{if(!loaded)return;try{localStorage.setItem(STORAGE,JSON.stringify({version:1,cases,events}))}catch{toast.error('Browser storage is unavailable. Progress will last for this session only.')}},[cases,events,loaded]);
 function log(caseId:string,action:string,detail:string,actor='Demo agent'){setEvents(old=>[...old,{id:crypto.randomUUID(),at:new Date().toISOString(),caseId,actor,action,detail}])}
 function update(id:string,patch:Partial<PatientCase>){setCases(old=>old.map(p=>p.id===id?{...p,...patch}:p))}
 function run(id:string){const p=cases.find(x=>x.id===id);if(!p||busy.current||!['new','paused'].includes(p.status))return;busy.current=true;update(id,{status:'running'});log(id,'Workflow started','Scenario fixture: '+p.scenario+'. No live model or external service is called.','Workflow');
  const blocked=['urgent','injection','unavailable'].includes(p.scenario);
  const stages=p.scenario==='urgent'?[['Risk signal identified','Original message contains a fixture-defined urgent safety concern.','safety_check'],['Routine drafting stopped','No reassuring draft was created. SAFE-01 applies.','safety_check']]:p.scenario==='injection'?[['Untrusted instruction detected','Attempt to override approval and access another patient was isolated.','input_guard'],['Cross-patient access blocked','No patient lookup executed. SEC-01 applies.','access_guard']]:[['Patient records retrieved','Read-only lookup scoped to '+p.id+'.','patient_lookup'],[p.scenario==='unavailable'?'Source unavailable':'Policy retrieved',p.scenario==='unavailable'?'Required procedure guidance unavailable. No unsupported draft created.':'Retrieved '+p.sources.join(', ')+'. Exact source excerpts are available.','guideline_search']];
  stages.forEach((s,i)=>timers.current.push(setTimeout(()=>log(id,s[0],s[1],s[2]),450*(i+1))));
  timers.current.push(setTimeout(()=>{update(id,{status:blocked?'blocked':'review'});log(id,blocked?'Safety stop — staff action needed':'Awaiting your review',blocked?p.summary:'Draft prepared. Human approval required before simulated sending.','Workflow');busy.current=false},450*(stages.length+1)));
 }
 function edit(id:string,draft:string){update(id,{draft})}
 function approve(id:string,acknowledged:boolean){const p=cases.find(x=>x.id===id);if(!p||p.status!=='review'||!acknowledged||!p.draft.trim())return false;const waiting=p.scenario==='missing'&&!p.followUp;update(id,{status:waiting?'awaiting':'sent'});log(id,waiting?'Clarification approved':'Reply approved',`Reviewer: Mia Chen. Sources: ${p.sources.join(', ')}. Final draft: ${p.draft}`,'Mia Chen');log(id,waiting?'Waiting for patient information':'Simulated reply sent','Local demonstration only. No actual patient message was sent.','Workflow');toast.success(waiting?'Clarification approved. Case saved while waiting.':'Reply approved and added to the simulated conversation.');return true}
 function decide(id:string,action:'escalated'|'rejected',note:string,team:string){const p=cases.find(x=>x.id===id);if(!p||!['review','blocked'].includes(p.status)||!note.trim())return false;update(id,{status:action,reviewerNote:note});log(id,action==='escalated'?'Case escalated':'Draft rejected',`${action==='escalated'?'Assigned to '+team+'. ':''}${note} No reply sent.`,'Mia Chen');toast.success(action==='escalated'?`Handoff recorded for ${team}.`:'Draft rejected. No reply sent.');return true}
 function followUp(id:string){const p=cases.find(x=>x.id===id);if(!p||p.status!=='awaiting'||p.scenario!=='missing')return;const message='It was my new iron tablet yesterday evening. I meant a metallic taste, which has gone away. I feel fine now.';update(id,{followUp:message,status:'paused',summary:'The patient has supplied the medication, timing and symptom description. Resume the workflow to prepare a staff-reviewed acknowledgement.',draft:'Hi Aisha, thank you for clarifying that you noticed a metallic taste after your new iron tablet and that this has now resolved. We will share your update with the care team for review. [1]\n\nKind regards,\nHarbour Primary Care',steps:['Read the new patient information','Recheck the message against the demo safety policy','Prepare an acknowledgement for clinician review']});log(id,'Patient follow-up received',message,'Simulated patient');toast.success('Demo patient response added. Resume triage to continue.')}
 function reset(){timers.current.forEach(clearTimeout);timers.current=[];busy.current=false;setCases(seedCases);setEvents(initialEvents);toast.success('Demo reset. All six scenarios are ready.')}
 return {cases,events,loaded,run,edit,approve,decide,followUp,reset};
}
