'use client';
import { useEffect, useRef, useState } from 'react';
import { flushSync } from 'react-dom';
import { Inbox, TriangleAlert, ShieldPlus, Building2, HelpCircle, RotateCcw, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Sidebar,SidebarProvider,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger } from '@/components/ui/sidebar';
import { Toaster } from 'sonner';
import { PatientCase,sourceFor } from './data';
import { InboxPanel } from './inbox-panel';
import { CasePanel } from './case-panel';
import { ActionDialogs,SourceDialog,DialogKind } from './dialogs';
import { useDemoStore } from './use-demo-store';
import { EngineControls, initialSettings, saveSettings } from './engine-controls';
import type { EngineSettings } from '../../shared/triage';
const navigation=[{id:'inbox',label:'Inbox',title:'Patient inbox',icon:Inbox},{id:'escalations',label:'Escalations',title:'Escalations',icon:TriangleAlert}];
export default function Workbench(){
 const [settings,setSettings]=useState(initialSettings);
 function change(next:EngineSettings){saveSettings(next);setSettings(next)}
 return <Workspace key={settings.mode+settings.apiUrl} settings={settings} onSettings={change}/>;
}
function Workspace({settings,onSettings}:{settings:EngineSettings;onSettings:(s:EngineSettings)=>void}){
 const store=useDemoStore(settings); const {cases}=store;
 const [selected,setSelected]=useState('PT-1042');const [view,setView]=useState('inbox');const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');const [mobileDetail,setMobileDetail]=useState(false);const [dialog,setDialog]=useState<DialogKind>(null);const [sourceId,setSourceId]=useState<string|null>(null);const [note,setNote]=useState('');const [team,setTeam]=useState('On-call clinician');
 const patient=cases.find(p=>p.id===selected)!;const busy=cases.some(p=>p.status==='running');const source=sourceId?sourceFor(sourceId,patient):undefined;
 function choose(p:PatientCase){setSelected(p.id);setMobileDetail(true)}
 function navigate(next:string){setView(next);setFilter('all');setQuery('');setMobileDetail(false);if(next==='escalations'){const first=cases.find(p=>p.status==='escalated'||p.status==='blocked');if(first)setSelected(first.id)}}
 function openDecision(kind:DialogKind){setDialog(kind);setNote('');setTeam(patient.scenario==='injection'?'Security review team':'On-call clinician')}
 function confirm(){let done=true;if(dialog==='escalate')done=store.decide(selected,'escalated',note,team);if(dialog==='reset'){store.reset();setSelected('PT-1042');navigate('inbox')}if(done){setDialog(null)}}
 const current=useRef({cases,choose,mode:settings.mode});current.current={cases,choose,mode:settings.mode};
 useEffect(()=>{const mc=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!mc?.registerTool)return;const lifecycle=new AbortController();const definitions=[{name:'read_demo_case_queue',description:'Read the fictional SafeTriage case queue and statuses. No real medical data.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({mode:current.current.mode,cases:current.current.cases.map(p=>({id:p.id,name:p.name,status:p.status,scenario:p.scenario}))})},{name:'open_demo_case',description:'Open a fictional case in the visible inbox. Does not triage, approve or send.',inputSchema:{type:'object',properties:{caseId:{type:'string'}},required:['caseId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const id=(input as {caseId?:unknown})?.caseId;if(typeof id!=='string')throw new Error('caseId must be a string');const found=current.current.cases.find(p=>p.id===id);if(!found)throw new Error('Unknown demo case');flushSync(()=>{setView('inbox');setFilter('all');setQuery('');current.current.choose(found)});return {opened:found.id,status:found.status,mode:current.current.mode}}}];for(const tool of definitions){try{Promise.resolve(mc.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{/* optional browser API */})}catch{/* unsupported browser */}}return()=>lifecycle.abort()},[]);
 return <SidebarProvider style={{'--sidebar-width':'204px'} as React.CSSProperties}><Sidebar className="app-sidebar"><SidebarHeader><div className="brand"><span className="brand-mark"><ShieldPlus size={24}/></span>SafeTriage</div></SidebarHeader><SidebarContent><SidebarMenu>{navigation.map(item=><SidebarMenuItem key={item.id}><SidebarMenuButton isActive={item.id===view} onClick={()=>navigate(item.id)}><item.icon/><span>{item.label}</span>{item.id==='inbox'&&<span className="nav-count">{cases.length}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-note"><ShieldCheck size={17}/><p>Clinical decisions.<br/><strong>Human oversight.</strong></p></div></SidebarContent><SidebarFooter><button className="help-link" onClick={()=>setDialog('guide')}><HelpCircle size={17}/>Demo guide</button><div className="user-profile"><span>MC</span><div><strong>Mia Chen</strong><small>Registered nurse</small></div></div></SidebarFooter></Sidebar><main className="app-main"><header className="topbar"><div className="title-row"><SidebarTrigger className="mobile-menu"/><h1>{navigation.find(n=>n.id===view)?.title}</h1></div><div className="topbar-right"><EngineControls settings={settings} onChange={onSettings} busy={busy}/><span className="clinic-name"><Building2 size={16}/>Harbour Primary Care</span><button className="demo-label" onClick={()=>setDialog('guide')}>Demo workspace</button><Button variant="ghost" size="icon" aria-label="Reset demo" onClick={()=>setDialog('reset')}><RotateCcw/></Button></div></header><div className={`workspace ${mobileDetail?'show-detail':''}`}><InboxPanel cases={cases} selected={selected} query={query} onQuery={setQuery} filter={filter} onFilter={setFilter} onSelect={choose} view={view}/><CasePanel mode={settings.mode} onMessage={message=>store.message(selected,message)} patient={patient} onBack={()=>setMobileDetail(false)} onContext={()=>setDialog('patient')} onSource={setSourceId} onEdit={draft=>store.edit(selected,draft)} onRun={()=>store.run(selected)} onApprove={()=>store.approve(selected)} onEscalate={()=>openDecision('escalate')} onReject={()=>store.decide(selected,'rejected','Rejected by reviewer.','')} onFollowUp={message=>store.followUp(selected,message)} busy={busy}/></div><footer className="app-footer"><ShieldCheck size={13}/>{settings.mode==='live'?'Live AI · Fictional data · Human review required.':'Demo · Fictional data · Replies are not sent.'}<span>CA6117 · Interactive prototype</span></footer></main><SourceDialog source={source} onClose={()=>setSourceId(null)}/><ActionDialogs mode={settings.mode} kind={dialog} onClose={()=>setDialog(null)} patient={patient} note={note} setNote={setNote} team={team} setTeam={setTeam} onConfirm={confirm} onSelect={p=>{navigate('inbox');choose(p)}}/><Toaster position="bottom-right" richColors/></SidebarProvider>
}
